# Generated by Django 5.1.1 on 2024-09-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
